image: node:latest

frontend_linting:
  stage: frontend_linting
  script:
    - yarn add eslint
    - yarn add eslint-plugin-react@latest
    - yarn add eslint-plugin-react-hooks@latest
    - yarn add @typescript-eslint/eslint-plugin@latest
    - yarn add typescript
    - yarn add @typescript-eslint/parser
    - ./node_modules/.bin/eslint frontend
  only:
    changes:
      - frontend/*

frontend_build:
  stage: frontend_build
  dependencies:
    - frontend_linting
  script:
    - cd frontend
    - yarn install --frozen-lockfile
    - yarn export
    - ls -al
  artifacts:
    untracked: true
  only:
    changes:
      - frontend/*

frontend_deploy_to_s3:
  stage: frontend_deploy_to_s3
  dependencies:
    - frontend_linting
    - frontend_build
  script:
    #
    # export DEV/TEST related variables if we are in that environment
    #
    - if [[ ${ENV} == "test" ]] ; then export AWS_ACCESS_KEY_ID=$TEST_CICD_USER_AWS_ACCESS_KEY_ID ; echo "exported" ; fi
    - if [[ ${ENV} == "test" ]] ; then export AWS_SECRET_ACCESS_KEY=$TEST_CICD_USER_AWS_SECRET_ACCESS_KEY ; fi
    - if [[ ${ENV} == "test" ]] ; then export AWS_DEFAULT_REGION=$TEST_AWS_DEFAULT_REGION ; fi
    - if [[ ${ENV} == "test" ]] ; then export AWS_S3_WEBSITE_TARGET_BUCKET=$TEST_S3_WEBSITE_TARGET_BUCKET ; fi
    #
    # export PROD related variables if we are in that environment. At this point we are using same credentials, because we only have 1 AWS account
    #
    - if [[ ${PROD} == "prod" ]] ; then export AWS_ACCESS_KEY_ID=$TEST_CICD_USER_AWS_ACCESS_KEY_ID ; fi
    - if [[ ${PROD} == "prod" ]] ; then export AWS_SECRET_ACCESS_KEY=$TEST_CICD_USER_AWS_SECRET_ACCESS_KEY ; fi
    - if [[ ${PROD} == "prod" ]] ; then export AWS_DEFAULT_REGION=$TEST_AWS_DEFAULT_REGION ; fi
    - if [[ ${PROD} == "prod" ]] ; then export AWS_S3_WEBSITE_TARGET_BUCKET=$PROD_S3_WEBSITE_TARGET_BUCKET ; fi
    #
    # Do actual upload
    #
    - apt update ; apt install -y python3-pip
    - pip3 install awscli
    - pwd
    - ls -al frontend
    - ls -al frontend/dist
    - cd frontend/dist
    - aws s3 ls s3://pasero.me.uk
    - aws s3 sync . s3://pasero.me.uk --delete --region us-east-1
  only:
    changes:
      - frontend/*
