version: '2.3'
services:

  test:
    build:
      context: ./
      dockerfile: ./tests/functionality/Dockerfile
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8083"]
    depends_on:
      - couchbase

  app:
    build: ./
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080"]
    depends_on:
      - couchbase

  couchbase:
    build: ./database/
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    hostname: couchbase
    entrypoint: /configure.sh